name: Deploy Prod
on:
  workflow_run:
    types: [completed]
jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: octomatch
          path: website
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}